version: '3.1'

services:

  web:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
    - ./db:/var/lib/postgres/pgdata
    - ./nasabah.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080